sudo: required
services:
  - docker

before_install:
  - docker build -t shashankpatel/docker-react -f Dockerfile.dev .

script:
  - docker run shashankpatel/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-729702393031"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_access_key
  secret_access_key: 
    secure: "$AWS_secret_key"

